### ISSUE TITLE
MSH-24.2 should not be required in the MSH segment

### ISSUE THREAD

**Issue by sueschm** [LinuxForHealth/hl7v2-fhir-converter#76] opened 2021-04-09 14:16 UTC
**Describe the bug**
Currently MSH-24.2 is required in the Message Header. The HL7 spec lists this as an Optional field so it shouldn't be required.

**To Reproduce**
Any HL7 message without a field entry in MSH-24.2 will fail conversion

**Expected behavior**
Any HL7 message without a field entry in MSH-24.2 should convert

**Desktop (please complete the following information):**
 - OS: Windows
 -  Latest version of the converter

**Comment by pbhallam** [comment] 2021-04-13 07:00
Here is the link for MessageHeader resource  https://www.hl7.org/fhir/messageheader.html
This resource requires source attribute which in turn requires endpoint to be present. Endpoint is extracted from MSH-24.2. So unless MSH-24.2. specified, MessageHeader cannot be extracted.  But as mentioned above, MSH-24 is optional field and may or may not be populated, it would be beneficial to pass optional attribute to the converter to use during conversion to populate this field.

**Comment by pbhallam** [comment] 2021-05-25 01:38
@sueschm  If you agree with my above comments then I can close this.

**Comment by LisaWellman** [comment] 2021-05-25 13:19
Pushpa I am not sure what you are proposing.  Are you suggesting the use fill in this field (no change to the code) before converting?  Or that there be a configuration flag to allow this field to be blank, or a default value in case it is blank?

**Comment by lisadier** [comment] 2021-09-16 19:24
We are not able to reproduce this on current code levels, so we are closing the issue.

**Closed** 2021-09-16 19:28 UTC

**Comment by MarceloLaser** [comment] 2024-04-11 23:49
Apologies for re-opening an issue from two years ago. I have run into the same problem described in this issue, that is, that the `MessageHeader` resource is not created when `MSH.24` is absent. This is due to `MSH.24.2` being `required` in `secondary/Source.yml`. The specification listed by @pbhallam (https://www.hl7.org/fhir/messageheader.html) marks `source` as required, but not `endpoint`. Also, `secondary/Destination.yml` has a different format for its `endpoint`, despite being represented the same way in HL7v2: for `Destination`, it allows the converter to fall back on `MSH.6` if `MSH.25` is absent.

To clarify, the faulty behavior is not that the conversion fails altogether, but rather that a FHIR bundle is generated without a `MessageHeader` resource. This may be why you were unable to reproduce the issue. I am currently running into the same problem when using either the source code from the current master branch, or the version 1.1.0 dependency from Maven Central (https://mvnrepository.com/artifact/io.github.linuxforhealth/hl7v2-fhir-converter/v1.1.0).

My recommendation would be to unmark `endpoint` in both `Source.yml` and `Destination.yml` as `required`, and to either modify `Source.yml` to allow falling back on `MSH.4`, or modify `Destination.yml` to disallow falling back on `MSH.6` (this option seems more in line with the FHIR specification). I'd be happy to send in a PR making these changes, if there is agreement that it is an appropriate solution.
