### ISSUE TITLE
ORC support for medication request

### ISSUE THREAD

**Issue by jgrant22** [LinuxForHealth/hl7v2-fhir-converter#317] opened 2021-10-28 14:29 UTC
**issue**
Add ORC segments converted to FHIR to the Medication Request request resource so users can create the resource with information from the ORC segment.

**Expected behavior**
Converter supports the ORC segments in medication request 
the support should work with every message even that includes a medication request resource

**Comment by LisaWellman** [comment] 2021-11-03 02:58
Duplicate of issue [334](https://github.com/LinuxForHealth/hl7v2-fhir-converter/issues/334), included in release 1.0.13

**Closed by LisaWellman** 2021-11-03 02:58 UTC
Labels: enhancement, FIXED
